name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every midnight UTC
  workflow_dispatch:       # Allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pritu761
          outputs: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg

      - name: Deploy to GitHub Pages (output branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}   # <--- use your PAT here
          publish_dir: dist
          publish_branch: output
